name: public to maven central repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: permissions
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3

#      - name: Import GPG key
#        uses: crazy-max/ghaction-import-gpg@v6
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.PASSPHRASE }}


      - name: Export secring.gpg
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private.pgp

      - name: set gradle.properties
        run: |
            echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
            echo "signing.password=${{ secrets.PASSPHRASE }}" >> gradle.properties
            echo "signing.secretKeyRingFile=./private.pgp" >> gradle.properties
            echo "mavenCentralUsername=${{ secrets.MAVEN_USERNAME }}" >> gradle.properties
            echo "mavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}" >> gradle.properties
          

      - name: Publish to Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache
